# Board: Heltec WiFi LoRa 32 (V2)
# Definition: definitions/boards/heltec_wifi_lora_32_V2/manifest.yaml

esphome:
  name: lora32-irrigazione
  friendly_name: LoRa32_Irrigazione

esp32:
  variant: esp32

logger:
  baud_rate: 0 #disable log via Uart 0

api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret lora32_irrigazione__ota_password

wifi:
  ssid: !secret wifi_wind_ssid
  password: !secret wifi_wind_password
  ap:
    ssid: LoRa32_Irrigazi Fallback Hotspot
    password: "BcBixd8e8793"

captive_portal:
  
uart:
  id: uart_0
  baud_rate: 115200
  rx_pin: GPIO3
  tx_pin: GPIO1
  debug:
    direction: BOTH
    debug_prefix: "UART:"
    dummy_receiver: true
    
sx127x:
  dio0_pin: GPIO26
  cs_pin: GPIO18
  rst_pin: GPIO14
  pa_pin: BOOST
  pa_power: 4
  bandwidth: 250_0kHz
  crc_enable: true
  frequency: 868300000Hz
  modulation: LORA
  rx_start: true
  sync_value: 0x33
  spreading_factor: 7
  coding_rate: CR_4_5
  on_packet:
    then:
      - lambda: |-
          char hex[256];  // Size appropriately for your data
          ESP_LOGD("lambda", "packet %s", format_hex_to(hex, x));
          ESP_LOGD("lambda", "rssi %.2f", rssi);
          ESP_LOGD("lambda", "snr %.2f", snr);

  spi_id: spi_1
  preamble_detect: 0
  packet_mode: true
  bitsync: true
  preamble_size: 6

web_server:
  auth:
    type: digest
    password: !secret web_server_password
    username: admin
    
button:
    - platform: template
      name: "Transmit Packet"
      on_press:
        then:
          - sx127x.send_packet:
              - 197
              - 81
              - 120
              - 130
              - 183
              - 249
              - 156
              - 92
          - uart.write: Ciao KC \n\l
              

spi:
  - id: spi_1
    clk_pin: 5
    miso_pin: 19
    mosi_pin: 27

i2c:
  scl: GPIO15
  sda: GPIO4
  id: i2c_0

font:
  - file: Google_Sans_Medium.ttf
    id: my_font
    size: 12

display:
  - platform: ssd1306_i2c
    id: display_ssd1306_i2c_1
    model: SSD1306_128X64
    i2c_id: i2c_0
    reset_pin: GPIO16
    lambda: |-
        it.print(0, 0, id(my_font), "state: ON");
    
  
  